// Mocks generated by Mockito 5.4.2 from annotations
// in invisquery/test/Features/Auth/Page/Bloc/login_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:invisquery/Core/Errors/failure.dart' as _i7;
import 'package:invisquery/Core/Network/network.dart' as _i2;
import 'package:invisquery/Core/utils/stroage.dart' as _i3;
import 'package:invisquery/Features/Auth/Data/DataSource/auth_repo_impl.dart'
    as _i4;
import 'package:invisquery/Features/Auth/Data/Models/auth_model.dart' as _i8;
import 'package:invisquery/Features/Auth/Data/Models/user_model.dart' as _i5;
import 'package:invisquery/Features/Auth/Domain/Reposatiory/auth_use_cases.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNetworkServiceImpl_0 extends _i1.SmartFake
    implements _i2.NetworkServiceImpl {
  _FakeNetworkServiceImpl_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageService_1 extends _i1.SmartFake
    implements _i3.StorageService {
  _FakeStorageService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepoImpl extends _i1.Mock implements _i4.AuthRepoImpl {
  MockAuthRepoImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NetworkServiceImpl get networkService => (super.noSuchMethod(
        Invocation.getter(#networkService),
        returnValue: _FakeNetworkServiceImpl_0(
          this,
          Invocation.getter(#networkService),
        ),
      ) as _i2.NetworkServiceImpl);
  @override
  _i3.StorageService get storageService => (super.noSuchMethod(
        Invocation.getter(#storageService),
        returnValue: _FakeStorageService_1(
          this,
          Invocation.getter(#storageService),
        ),
      ) as _i3.StorageService);
  @override
  set accessToken(String? _accessToken) => super.noSuchMethod(
        Invocation.setter(
          #accessToken,
          _accessToken,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set user(_i5.UserModel? _user) => super.noSuchMethod(
        Invocation.setter(
          #user,
          _user,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.Future<(_i7.Failure?, _i8.AuthModel?)> login(
    String? email,
    String? password,
    String? fcmToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
            fcmToken,
          ],
        ),
        returnValue:
            _i6.Future<(_i7.Failure?, _i8.AuthModel?)>.value((null, null)),
      ) as _i6.Future<(_i7.Failure?, _i8.AuthModel?)>);
  @override
  _i6.Future<(_i7.Failure?, _i8.AuthModel?)> anonymous(String? fcmToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #anonymous,
          [fcmToken],
        ),
        returnValue:
            _i6.Future<(_i7.Failure?, _i8.AuthModel?)>.value((null, null)),
      ) as _i6.Future<(_i7.Failure?, _i8.AuthModel?)>);
  @override
  _i6.Future<_i7.Failure?> deleteUser() => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [],
        ),
        returnValue: _i6.Future<_i7.Failure?>.value(),
      ) as _i6.Future<_i7.Failure?>);
  @override
  _i6.Future<(_i7.Failure?, _i5.UserModel?)> getUser() => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [],
        ),
        returnValue:
            _i6.Future<(_i7.Failure?, _i5.UserModel?)>.value((null, null)),
      ) as _i6.Future<(_i7.Failure?, _i5.UserModel?)>);
  @override
  _i6.Future<_i7.Failure?> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i6.Future<_i7.Failure?>.value(),
      ) as _i6.Future<_i7.Failure?>);
  @override
  _i6.Future<_i7.Failure?> resetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i6.Future<_i7.Failure?>.value(),
      ) as _i6.Future<_i7.Failure?>);
  @override
  _i6.Future<(_i7.Failure?, _i8.AuthModel?)> signUp(
    String? email,
    String? password,
    String? fcmToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [
            email,
            password,
            fcmToken,
          ],
        ),
        returnValue:
            _i6.Future<(_i7.Failure?, _i8.AuthModel?)>.value((null, null)),
      ) as _i6.Future<(_i7.Failure?, _i8.AuthModel?)>);
  @override
  _i6.Future<(_i7.Failure?, _i8.AuthModel?)> socialLogin(
    String? email,
    String? provider,
    String? privateProfileImage,
    String? fcmToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #socialLogin,
          [
            email,
            provider,
            privateProfileImage,
            fcmToken,
          ],
        ),
        returnValue:
            _i6.Future<(_i7.Failure?, _i8.AuthModel?)>.value((null, null)),
      ) as _i6.Future<(_i7.Failure?, _i8.AuthModel?)>);
  @override
  _i6.Future<(_i7.Failure?, _i8.AuthModel?)> loginHelper({
    required _i9.AuthUseCase? useCase,
    required String? endpoint,
    String? email,
    String? password,
    String? fcmToken,
    String? provider,
    String? privateProfileImage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginHelper,
          [],
          {
            #useCase: useCase,
            #endpoint: endpoint,
            #email: email,
            #password: password,
            #fcmToken: fcmToken,
            #provider: provider,
            #privateProfileImage: privateProfileImage,
          },
        ),
        returnValue:
            _i6.Future<(_i7.Failure?, _i8.AuthModel?)>.value((null, null)),
      ) as _i6.Future<(_i7.Failure?, _i8.AuthModel?)>);
  @override
  _i6.Future<(_i7.Failure?, String?)> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i6.Future<(_i7.Failure?, String?)>.value((null, null)),
      ) as _i6.Future<(_i7.Failure?, String?)>);
  @override
  _i6.Future<_i7.Failure?> logoutHelper() => (super.noSuchMethod(
        Invocation.method(
          #logoutHelper,
          [],
        ),
        returnValue: _i6.Future<_i7.Failure?>.value(),
      ) as _i6.Future<_i7.Failure?>);
  @override
  _i6.Future<Map<String, String>> getHeaderWithToken() => (super.noSuchMethod(
        Invocation.method(
          #getHeaderWithToken,
          [],
        ),
        returnValue: _i6.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i6.Future<Map<String, String>>);
}
