name: Test

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2


      - name: Restore packages
        run: flutter pub get  # Use 'flutter pub get' to restore packages

      - name: Run tests with coverage
        run: flutter test --coverage


